ARM MAP and minor changes
nesi/perf-training pull request #45
Opened 2019-01-03 22:51 UTC by mand35

2019-01-04 02:24 UTC, pletzer requested changes
Hi @mand35. Thanks for adding the ARM info.

1. 01-profiling.md line 19: "This can be a function, loop, or source code line based." (add article "a").

2. lines 23-24. I prefer the original version because by saying "The profiler can add significant overhead" this could be interpreted as "the numbers returned by the profiler are wrong". 

3. Line 38. Remove "Basically" and replace "spend" with "spent"

4. Line 40. Is it really true that the profiler adds significant overhead? If I'm not mistaken some profilers take into account their own overhead when returning timings. I'm wondering whether we want to mention this part.... 

5. Line 112. optimized -> optimised

6. There is another PR regarding the mpi section, which will be merged  sometime and may interfere with this PR. I suggest you create another branch and open another PR for the mpi section. Also we typically have a sentence at the top "Start by changing directory to blah blah". I understand it makes sense to change the directory after introducing the concepts but then this would be done in all lessons (a separate PR).

2019-01-04 03:36 UTC, mand35 commented
done

2019-01-06 03:15 UTC, pletzer reviewed
* Somehow we need to differentiate cProfile from MAP. 
  - When should cProfile be used and when should MAP be used? (cProfile can run on any serial Python code. It can be used to identify the functions that take most of the execution time. MAP is a commercial product installed on Mahuika, which can provide profiling information for any program, whether it is written Python or C/C++, and whether it is runs serially or in parallel. MAP supports MPI, OpenMP and Cuda. A graphical interface allows the user to focus on specific source lines, .... (list all the features here). Because MAP is a graphical tool, it can on the other hand slow over the network.

* I'm also thinking that how to use MAP is a big topic that deserves a separate lesson. We'll have to describe each step carefully with many screen shots.

* Keep in mind that we use English spelling - parrallelised instead of parallelized.

2019-01-06 08:50 UTC, mand35 commented
I added more details to the MAP description. Yes, I will add NeSI documentation for MAP. But I think for this context a short description on how to run map is sufficient. The GUI is user-friendly and fairly straight forward to use. It could be more of interest to interpret the presented data.

2019-01-06 18:18 UTC, pletzer commented
Here are my recommendations:

1. Create a separate lesson 01b-profiling-with-map
2. Have Pros and Cons of MAP
3. Describe how to use MAP, including how to submit a parallel job. Include screen shots
4. Have an exercise section where student profiles the openmp version of scatter.

2019-01-07 00:50 UTC, chrisdjscott commented on _lessons/python-scatter/01-profiling.md
> +[![example-map-scatter](images/MAP_scatter.png)](images/MAP_scatter.png)
@mand35 the case of the MAP_scatter image is not correct in the link - you either need to rename the file from MAP_scatter.PNG -> MAP_scatter.png, or edit the link to make it MAP_scatter.PNG

2019-01-07 02:24 UTC, chrisdjscott commented
Thanks @mand35

2019-01-07 02:25 UTC, merged