Ctypes review
nesi/perf-training pull request #59
Opened 2019-01-16 23:19 UTC by pletzer

Aligned the code to the numba example. Found that there are subtle aspects we need to be aware of, namely numpy.int arrays are actually long long arrays. A little unfortunate.... Still need to go through the example

2019-01-17 21:26 UTC, chrisdjscott requested changes
@pletzer some minor changes suggested below.

I would also suggest to change `libfile = glob.glob('build/*/*.so')[0]` to `libfile = glob.glob('build/*/mysum*.so')[0]` as this would work if there were multiple C extensions.

Do you think we give enough detail in the exercise? I guess for people who have never used C before it might be a difficult one. We could give a bit more info on point 2, e.g. "create a new file in src directory and put the C function in it; make sure to add this file to the wave extension in setup.py". Or do you think it's better to try and get people to figure this out for themselves?

2019-01-17 21:26 UTC, chrisdjscott commented on _lessons/python-scatter/03b-ctypes.md
> + 3. It make your code type safe. In contrast to C, C++ and Fortran, Python is not a typed language - you can pass any object to any Python function.  This can cause runtime failures in Python which c
```suggestion
 3. It makes your code type safe. In contrast to C, C++ and Fortran, Python is not a typed language - you can pass any object to any Python function.  This can cause runtime failures in Python which cannot occur in C, C++ or Fortran, as the error would be caught by the compiler
```

2019-01-17 21:26 UTC, chrisdjscott commented on _lessons/python-scatter/03b-ctypes.md
>   2. You have identified a performance bottleneck - reimplementing some parts of your Python code in C, C++ or Fortran will give you a performance boost
It's not guaranteed

```suggestion
 2. You have identified a performance bottleneck - reimplementing some parts of your Python code in C, C++ or Fortran could give you a performance boost
```

2019-01-17 21:26 UTC, chrisdjscott commented on _lessons/python-scatter/03b-ctypes.md
> + * By default, arguments are passed by value. To pass an array of ints (`int*`), specify `numpy.ctypeslib.ndpointer(dtype=numpy.int32)` in the `argtypes` list. You can declare `double*` similarly by
```suggestion
 * By default, arguments are passed by value. To pass an array of ints (`int*`), specify `numpy.ctypeslib.ndpointer(dtype=numpy.int32)` in the `argtypes` list. You can declare `double*` similarly by using `numpy.ctypeslib.ndpointer(dtypes=numpy.float64)`
```

2019-01-18 02:18 UTC, pletzer commented
Thanks for your suggestions.

2019-01-18 02:19 UTC, merged